#!/bin/bash
#
# chkconfig: 2345 85 15
# description: Supervisord Process Management daemon 
#
# Get function from functions library
. /etc/init.d/functions

APPDIR=/opt/internet2/grouper/changelogger/supervisor
PIDFILE=/tmp/supervisord.pid
START_SCRIPT="$APPDIR/start.sh"
STOP_SCRIPT="$APPDIR/stop.sh"
LOCK_FILE="/var/lock/subsys/supervisor"
SUCCESS_MSG="supervisord startup"
USER=grouper
SUDO=/usr/bin/sudo

# Start the service 
start() {
        echo -n "Starting supervisord service: "
        "$SUDO" -i -u "$USER" "$START_SCRIPT"
        ### Create the lock file ###
        touch "$LOCK_FILE"
        success "$SUCCESS_MSG"
        echo
}
# Restart the service 
stop() {
        echo -n "Stopping server: "
        "$SUDO" -i -u "$USER" "$STOP_SCRIPT"
        ### Now, delete the lock file ###
        rm -f "$LOCK_FILE"
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status -p "$PIDFILE"
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac
exit 0

