#!/bin/bash
#
# chkconfig: 2345 85 15
# description: Twisted Group Server daemon 
#
# Get function from functions library
. /etc/init.d/functions

APPDIR=/opt/txgroupserver
PIDFILE="$APPDIR/twistd.pid"
START_SCRIPT="$APPDIR/start.sh"
STOP_SCRIPT="$APPDIR/stop.sh"
LOCK_FILE="/var/lock/subsys/txgroupserver"
SUCCESS_MSG="txgroupserver startup"

# Start the service 
start() {
        echo -n "Starting txgroupserver service: "
        "$START_SCRIPT"
        ### Create the lock file ###
        touch "$LOCK_FILE"
        success "$SUCCESS_MSG"
        echo
}
# Restart the service 
stop() {
        echo -n "Stopping server: "
        "$STOP_SCRIPT"
        ### Now, delete the lock file ###
        rm -f "$LOCK_FILE"
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status -p "$PIDFILE"
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0

