#! /bin/sh

THISDIR="$( cd $(dirname $0); pwd)"
SCRIPT="$THISDIR/$(basename $0)"
PYENV="$THISDIR/pyenv"
TWISTD="$THISDIR/twistd.sh"
PIDDIR="${PIDDIR:-/var/run/txgroupprovisioner}"

confd="$THISDIR/conf.d"
use_syslog=
syslog_prefix=txgroupprov
logfile=

function usage
{
    echo 
    echo "======================"
    echo "Run group provisioners"
    echo "======================"
    echo
    echo Usage: $0 '[OPTIONS]' '[CONF_DIR]' >&2
    echo
    echo == Options ==
    echo -l LOGFILE         \; Log to LOGFILE
    echo -s                 \; Log to syslog
}

while getopts :l:sh opt
do
    case "$opt" in
    l)      logfile="$OPTARG"
            ;;
    s)     use_syslog=1 ;;
    h)     usage; exit 0 ;;
    '?')    echo "$0: Invalid option -$OPTARG" >&2
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

if [ $# -gt 0 ]; then
    confd="$1"
fi
if [ ! -z "$use_syslog" ] && ! [ -z $logfile ]; then
    echo "Options -l and -s are mutually exclusive." >&2
    usage
    exit 1
fi
twistd_opt_syslog=
twistd_opt_logfile=
twistd_opt_logfile_arg=
if [ ! -z "$use_syslog" ]; then
    twistd_opt_syslog='--syslog'
elif [ ! -z "$logfile" ]; then
    twistd_opt_logfile="--logfile"
    twistd_opt_logfile_arg="$logfile"
fi
cd "$THISDIR"
. "$PYENV/bin/activate"
ls "$confd"/*.cfg | while read fname; do
    FNAME=$(basename "$fname")
    CONFIG="$confd/$FNAME"
    BASE=$(basename "$FNAME" .cfg)
    PIDFILE="$BASE.pid"
    if [ ! -z "$use_syslog" ]; then
        twistd_opt_prefix="--prefix"
        twistd_opt_prefix_arg="$BASE"
    fi
    "$TWISTD" \
        "$twistd_opt_syslog" "$twistd_opt_prefix" "$twistd_opt_prefix_arg" \
        "$twistd_opt_logfile" "$twistd_opt_logfile_arg" \
        --pidfile "$PIDFILE" provisioner -c "$CONFIG"
done

